development: &development
  adapter: postgresql
  database: db/development1
  username: abc
  password: password1
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: test_database_name

production:
  <<: *development
  database: production_db_name
