#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development: &development
  adapter: postgresql
  database: development1
  username: abc
  password: password1
  host:     localhost
  schema_search_path: public
  min_messages: warning


#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

test:
  <<: *development
  database: test_database_name

production:
  <<: *development
  database: production_db_name
