---
development:
  adapter: postgresql
  database: db/development1
  username: abc
  password: password1
  host: localhost
  schema_search_path: public
  min_messages: warning
test:
  adapter: postgresql
  database: test_database_name
  username: abc
  password: password1
  host: localhost
  schema_search_path: public
  min_messages: warning
production:
  adapter: postgresql
  database: production_db_name
  username: abc
  password: password1
  host: localhost
  schema_search_path: public
  min_messages: warning
user_base:
  adapter: postgresql
  database: d3a
  username: asdfasfss
  password: ''
  host: localhost
