---
development:
  adapter: postgresql
  database: development
  username: admin
  password: admin1
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: test_database_name
  username: admin
  password: admin1
  host: localhost
production:
  adapter: postgresql
  database: production_db_name
  username: admin
  password: admin1
  host: localhost
